<?php

if ( ! defined( 'ABSPATH' ) ) {
	die;
}

/**
 * Cart CSS options. Each id maps to a --woo-* custom property in
 * WOOCSSVARIABLE; leaving one empty keeps the stylesheet default.
 *
 * These apply to the classic cart table and, where WooCommerce allows it,
 * to the Cart block as well.
 */
$settings = array(
	array(
		'title' => __( 'Cart Table', 'woocustomcss' ),
		'type'  => 'title',
		'desc'  => __( 'Borders, colours and spacing for the cart and order tables.', 'woocustomcss' ),
		'id'    => 'cart_css_options',
	),
	array(
		'title'    => __( 'Table Border Size', 'woocustomcss' ),
		'desc'     => __( 'Width of the table borders.', 'woocustomcss' ),
		'id'       => 'table_border_size',
		'type'     => 'ms_size',
		'css'      => 'width:4em;',
		'default'  => '',
		'autoload' => false,
		'desc_tip' => true,
	),
	array(
		'title'    => __( 'Table Border Color', 'woocustomcss' ),
		'desc'     => __( 'Colour of the table borders.', 'woocustomcss' ),
		'id'       => 'table_bor_clr',
		'type'     => 'color',
		'css'      => 'width:6em;',
		'default'  => '',
		'autoload' => false,
		'desc_tip' => true,
	),
	array(
		'title'    => __( 'Table Border Radius', 'woocustomcss' ),
		'desc'     => __( 'Corner rounding of the table.', 'woocustomcss' ),
		'id'       => 'table_bor_radius',
		'type'     => 'ms_dimension',
		'css'      => 'width:4em;',
		'default'  => '',
		'autoload' => false,
		'desc_tip' => true,
	),
	array(
		'title'    => __( 'Table Heading Background Color', 'woocustomcss' ),
		'desc'     => __( 'Background colour of the table header row.', 'woocustomcss' ),
		'id'       => 'table_hbg_clr',
		'type'     => 'color',
		'css'      => 'width:6em;',
		'default'  => '',
		'autoload' => false,
		'desc_tip' => true,
	),
	array(
		'title'    => __( 'Table Heading Text Color', 'woocustomcss' ),
		'desc'     => __( 'Text colour of the table header row. Check this against the heading background for contrast.', 'woocustomcss' ),
		'id'       => 'table_htext_clr',
		'type'     => 'color',
		'css'      => 'width:6em;',
		'default'  => '',
		'autoload' => false,
		'desc_tip' => true,
	),
	array(
		'title'    => __( 'Table Heading Font Size', 'woocustomcss' ),
		'desc'     => __( 'Font size of the table header row.', 'woocustomcss' ),
		'id'       => 'table_head_size',
		'type'     => 'ms_size',
		'css'      => 'width:4em;',
		'default'  => '',
		'autoload' => false,
		'desc_tip' => true,
	),
	array(
		'title'    => __( 'Uppercase Table Headings', 'woocustomcss' ),
		'desc'     => __( 'Render the header row in uppercase. On by default.', 'woocustomcss' ),
		'id'       => 'table_head_upper',
		'default'  => 'yes',
		'type'     => 'checkbox',
		'autoload' => false,
	),
	array(
		'title'    => __( 'Table Text Color', 'woocustomcss' ),
		'desc'     => __( 'Text colour of the table body.', 'woocustomcss' ),
		'id'       => 'table_text_clr',
		'type'     => 'color',
		'css'      => 'width:6em;',
		'default'  => '',
		'autoload' => false,
		'desc_tip' => true,
	),
	array(
		'title'    => __( 'Table Row Background Color', 'woocustomcss' ),
		'desc'     => __( 'Background colour of the table body rows.', 'woocustomcss' ),
		'id'       => 'table_row_bg',
		'type'     => 'color',
		'css'      => 'width:6em;',
		'default'  => '',
		'autoload' => false,
		'desc_tip' => true,
	),
	array(
		'title'    => __( 'Table Cell Padding', 'woocustomcss' ),
		'desc'     => __( 'Inner spacing of the table cells.', 'woocustomcss' ),
		'id'       => 'table_cell_pad',
		'type'     => 'ms_dimension',
		'css'      => 'width:4em;',
		'default'  => '',
		'autoload' => false,
		'desc_tip' => true,
	),
	array(
		'title'    => __( 'Product Thumbnail Width', 'woocustomcss' ),
		'desc'     => __( 'Width of the product image column in the cart table.', 'woocustomcss' ),
		'id'       => 'table_thumb_width',
		'type'     => 'ms_size',
		'css'      => 'width:4em;',
		'default'  => '',
		'autoload' => false,
		'desc_tip' => true,
	),
	array(
		'type' => 'sectionend',
		'id'   => 'cart_css_options',
	),

	array(
		'title' => __( 'Remove Button', 'woocustomcss' ),
		'type'  => 'title',
		'desc'  => __( 'The small &times; that removes a line from the cart.', 'woocustomcss' ),
		'id'    => 'cart_remove_options',
	),
	array(
		'title'    => __( 'Remove Button Background', 'woocustomcss' ),
		'desc'     => __( 'Background colour of the remove button.', 'woocustomcss' ),
		'id'       => 'cart_remove_bg',
		'type'     => 'color',
		'css'      => 'width:6em;',
		'default'  => '',
		'autoload' => false,
		'desc_tip' => true,
	),
	array(
		'title'    => __( 'Remove Button Icon Color', 'woocustomcss' ),
		'desc'     => __( 'Colour of the &times; itself.', 'woocustomcss' ),
		'id'       => 'cart_remove_clr',
		'type'     => 'color',
		'css'      => 'width:6em;',
		'default'  => '',
		'autoload' => false,
		'desc_tip' => true,
	),
	array(
		'title'    => __( 'Remove Button Hover Background', 'woocustomcss' ),
		'desc'     => __( 'Background colour of the remove button on hover.', 'woocustomcss' ),
		'id'       => 'cart_remove_bg_hover',
		'type'     => 'color',
		'css'      => 'width:6em;',
		'default'  => '',
		'autoload' => false,
		'desc_tip' => true,
	),
	array(
		'type' => 'sectionend',
		'id'   => 'cart_remove_options',
	),

	array(
		'title' => __( 'Cart Totals', 'woocustomcss' ),
		'type'  => 'title',
		'desc'  => __( 'The totals panel beside or below the cart table.', 'woocustomcss' ),
		'id'    => 'cart_totals_options',
	),
	array(
		'title'    => __( 'Totals Background Color', 'woocustomcss' ),
		'desc'     => __( 'Background of the cart totals panel.', 'woocustomcss' ),
		'id'       => 'cart_totals_bg',
		'type'     => 'color',
		'css'      => 'width:6em;',
		'default'  => '',
		'autoload' => false,
		'desc_tip' => true,
	),
	array(
		'title'    => __( 'Totals Max Width', 'woocustomcss' ),
		'desc'     => __( 'How wide the totals panel is allowed to get on desktop.', 'woocustomcss' ),
		'id'       => 'cart_totals_width',
		'type'     => 'ms_size',
		'css'      => 'width:4em;',
		'default'  => '',
		'autoload' => false,
		'desc_tip' => true,
	),
	array(
		'title'    => __( 'Cart Heading Color', 'woocustomcss' ),
		'desc'     => __( 'Colour of the "Cart Title Text" heading set under Theme Hooks.', 'woocustomcss' ),
		'id'       => 'cart_title_clr',
		'type'     => 'color',
		'css'      => 'width:6em;',
		'default'  => '',
		'autoload' => false,
		'desc_tip' => true,
	),
	array(
		'title'    => __( 'Cart Heading Size', 'woocustomcss' ),
		'desc'     => __( 'Font size of the cart heading.', 'woocustomcss' ),
		'id'       => 'cart_title_size',
		'type'     => 'ms_size',
		'css'      => 'width:4em;',
		'default'  => '',
		'autoload' => false,
		'desc_tip' => true,
	),
	array(
		'type' => 'sectionend',
		'id'   => 'cart_totals_options',
	),
);
