<?php 
$settings = array(	
	array(
		'title' 	=> __( 'Cart CSS Options', 'woocustomcss' ),
		'type'  	=> 'title',
		'desc'  	=> '',
		'id'    	=> 'cart_css_options',
	),		
	array(
		'title'    	=> __( 'Table Border Size', 'woocustomcss' ),
		'desc'     	=> __( 'Select table border size for the cart page. The defalut color added by the WooCommerce CSS.', 'woocustomcss' ),
		'id'       	=> 'table_border_size',
		'type'     	=> 'ms_size',
		'css'      	=> 'width:4em;',
		'default'  	=> '',
		'autoload' 	=> false,
		'desc_tip' 	=> true,
	),			
	array(
		'title'    	=> __( 'Table Border Color', 'woocustomcss' ),
		'desc'     	=> __( 'Select color for buttons background color. The defalut color added by the WooCommerce CSS.', 'woocustomcss' ),
		'id'       	=> 'table_bor_clr',
		'type'     	=> 'color',
		'css'      	=> 'width:6em;',
		'default'  	=> '#000000',
		'autoload' 	=> false,
		'desc_tip' 	=> true,
	),
	array(
		'title'    	=> __( 'Table Heading Background Color', 'woocustomcss' ),
		'desc'     	=> __( 'Select color for table heading background color. The defalut color added by the WooCommerce CSS.', 'woocustomcss' ),
		'id'       	=> 'table_hbg_clr',
		'type'     	=> 'color',
		'css'      	=> 'width:6em;',
		'default'  	=> '#000000',
		'autoload' 	=> false,
		'desc_tip' 	=> true,
	),
	array(
		'title'    	=> __( 'Table Heading Text Color', 'woocustomcss' ),
		'desc'     	=> __( 'Select color for the cart table heading text color. The defalut color added by the WooCommerce CSS.', 'woocustomcss' ),
		'id'       	=> 'table_htext_clr',
		'type'     	=> 'color',
		'css'      	=> 'width:6em;',
		'default'  	=> '#000000',
		'autoload' 	=> false,
		'desc_tip' 	=> true,
	),
	array(
		'title'    	=> __( 'Table Text Color', 'woocustomcss' ),
		'desc'     	=> __( 'Select color for the cart table text color. The defalut color added by the WooCommerce CSS.', 'woocustomcss' ),
		'id'       	=> 'table_text_clr',
		'type'     	=> 'color',
		'css'      	=> 'width:6em;',
		'default'  	=> '#000000',
		'autoload' 	=> false,
		'desc_tip' 	=> true,
	),
	array(
		'type' => 'sectionend',
		'id'   => 'cart_css_options',
	),
);