<?php

if ( ! defined( 'ABSPATH' ) ) {
	die;
}

/**
 * Checkout CSS options. Each id maps to a --woo-* custom property in
 * WOOCSSVARIABLE; leaving one empty keeps the stylesheet default.
 */
$settings = array(
	array(
		'title' => __( 'Form Field Styling', 'woocustomcss' ),
		'type'  => 'title',
		'desc'  => __( 'Applies to the checkout, my-account and address forms, and to the block checkout where it allows it.', 'woocustomcss' ),
		'id'    => 'checkout_field_options',
	),
	array(
		'title'    => __( 'Field Border Color', 'woocustomcss' ),
		'desc'     => __( 'Border colour for text inputs, selects and textareas.', 'woocustomcss' ),
		'id'       => 'field_bordr_clr',
		'type'     => 'color',
		'css'      => 'width:6em;',
		'default'  => '',
		'autoload' => false,
		'desc_tip' => true,
	),
	array(
		'title'    => __( 'Field Background Color', 'woocustomcss' ),
		'desc'     => __( 'Background colour of form fields.', 'woocustomcss' ),
		'id'       => 'field_bg_clr',
		'type'     => 'color',
		'css'      => 'width:6em;',
		'default'  => '',
		'autoload' => false,
		'desc_tip' => true,
	),
	array(
		'title'    => __( 'Field Text Color', 'woocustomcss' ),
		'desc'     => __( 'Colour of text typed into form fields.', 'woocustomcss' ),
		'id'       => 'field_text_clr',
		'type'     => 'color',
		'css'      => 'width:6em;',
		'default'  => '',
		'autoload' => false,
		'desc_tip' => true,
	),
	array(
		'title'    => __( 'Field Focus Color', 'woocustomcss' ),
		'desc'     => __( 'Border and focus-ring colour when a field is selected. Keep this clearly visible — it is how keyboard users track where they are.', 'woocustomcss' ),
		'id'       => 'field_focus_clr',
		'type'     => 'color',
		'css'      => 'width:6em;',
		'default'  => '',
		'autoload' => false,
		'desc_tip' => true,
	),
	array(
		'title'    => __( 'Field Border Radius', 'woocustomcss' ),
		'desc'     => __( 'Corner rounding for form fields.', 'woocustomcss' ),
		'id'       => 'field_bor_radius',
		'type'     => 'ms_dimension',
		'css'      => 'width:4em;',
		'default'  => '',
		'autoload' => false,
		'desc_tip' => true,
	),
	array(
		'title'    => __( 'Field Height', 'woocustomcss' ),
		'desc'     => __( 'Minimum height of a single-line field. Values under 44px make fields harder to tap on a phone.', 'woocustomcss' ),
		'id'       => 'field_height',
		'type'     => 'ms_size',
		'css'      => 'width:4em;',
		'default'  => '',
		'autoload' => false,
		'desc_tip' => true,
	),
	array(
		'title'    => __( 'Label Color', 'woocustomcss' ),
		'desc'     => __( 'Colour of the field labels.', 'woocustomcss' ),
		'id'       => 'field_label_clr',
		'type'     => 'color',
		'css'      => 'width:6em;',
		'default'  => '',
		'autoload' => false,
		'desc_tip' => true,
	),
	array(
		'title'    => __( 'Label Font Weight', 'woocustomcss' ),
		'desc'     => __( 'Font weight of the field labels.', 'woocustomcss' ),
		'id'       => 'field_label_fw',
		'type'     => 'select',
		'options'  => array(
			''        => __( 'Default (600)', 'woocustomcss' ),
			'400'     => __( '400', 'woocustomcss' ),
			'500'     => __( '500', 'woocustomcss' ),
			'600'     => __( '600', 'woocustomcss' ),
			'700'     => __( '700', 'woocustomcss' ),
			'normal'  => __( 'normal', 'woocustomcss' ),
			'bold'    => __( 'bold', 'woocustomcss' ),
			'inherit' => __( 'inherit', 'woocustomcss' ),
		),
		'css'      => 'width:10em;',
		'default'  => '',
		'autoload' => false,
		'desc_tip' => true,
	),
	array(
		'type' => 'sectionend',
		'id'   => 'checkout_field_options',
	),

	array(
		'title' => __( 'Checkout Panels', 'woocustomcss' ),
		'type'  => 'title',
		'desc'  => __( 'The fieldsets, order review table and payment box.', 'woocustomcss' ),
		'id'    => 'checkout_panel_options',
	),
	array(
		'title'    => __( 'Panel Background Color', 'woocustomcss' ),
		'desc'     => __( 'Background of the fieldsets and the payment box.', 'woocustomcss' ),
		'id'       => 'checkout_panel_bg',
		'type'     => 'color',
		'css'      => 'width:6em;',
		'default'  => '',
		'autoload' => false,
		'desc_tip' => true,
	),
	array(
		'title'    => __( 'Panel Border', 'woocustomcss' ),
		'desc'     => __( 'Border around the fieldsets and the payment box.', 'woocustomcss' ),
		'id'       => 'checkout_panel_bor',
		'type'     => 'ms_border',
		'css'      => 'width:4em;',
		'default'  => '',
		'autoload' => false,
		'desc_tip' => true,
	),
	array(
		'title'    => __( 'Panel Border Radius', 'woocustomcss' ),
		'desc'     => __( 'Corner rounding of the fieldsets and the payment box.', 'woocustomcss' ),
		'id'       => 'checkout_panel_radius',
		'type'     => 'ms_dimension',
		'css'      => 'width:4em;',
		'default'  => '',
		'autoload' => false,
		'desc_tip' => true,
	),
	array(
		'title'    => __( 'Panel Padding', 'woocustomcss' ),
		'desc'     => __( 'Inner spacing of the fieldsets and the payment box.', 'woocustomcss' ),
		'id'       => 'checkout_panel_pad',
		'type'     => 'ms_dimension',
		'css'      => 'width:4em;',
		'default'  => '',
		'autoload' => false,
		'desc_tip' => true,
	),
	array(
		'title'    => __( 'Full Width Place Order Button', 'woocustomcss' ),
		'desc'     => __( 'Stretch the "Place order" button across the payment box. On by default.', 'woocustomcss' ),
		'id'       => 'checkout_place_order_full',
		'default'  => 'yes',
		'type'     => 'checkbox',
		'autoload' => false,
	),
	array(
		'type' => 'sectionend',
		'id'   => 'checkout_panel_options',
	),
);
