<?php
$settings = array(
    array(
        'title' 	=> __('Shop Page Category Loop CSS', 'woocustomcss') ,
        'type' 		=> 'title',
        'desc' 		=> '',
        'id' 		=> 'shop_cat_css_options',
    ),
	array(
        'title' 	=> __('Category Title Font Family', 'woocustomcss') ,
        'desc' 		=> __('Add here the Category text Font family CSS. Black set default from body.', 'woocustomcss') ,
        'id' 		=> 'cat_text_ff',
        'type' 		=> 'text',
        'css' 		=> 'width:20em;',
        'default' 	=> '',
        'autoload' 	=> false,
        'desc_tip' 	=> true,
    ),
    array(
        'title' 	=> __('Category Title Color', 'woocustomcss') ,
        'desc' 		=> __('Select product title color here.', 'woocustomcss') ,
        'id' 		=> 'cat_title_clr',
        'type' 		=> 'color',
        'css' 		=> 'width:6em;',
        'default' 	=> '#000000',
        'autoload' 	=> false,
        'desc_tip' 	=> true,
    ),
    array(
        'title' 	=> __('Category Title Size', 'woocustomcss') ,
        'desc' 		=> __('Select product title size in pixles.', 'woocustomcss') ,
        'id' 		=> 'cat_title_size',
        'type' 		=> 'ms_size',
        'css' 		=> 'width:4em;',
        'default' 	=> '',
        'autoload' 	=> false,
        'desc_tip' 	=> true,
    ),
	array(
        'title' 	=> __('Category Title Font Weight', 'woocustomcss') ,
        'desc' 		=> __('Add here the Category Title Font Weight CSS.', 'woocustomcss') ,
        'id' 		=> 'cat_title_fw',
        'type' 		=> 'select',
		'options'	=> array(
			'100'        => __( '100', 'woocustomcss' ),
			'200'        => __( '200', 'woocustomcss' ),
			'300'        => __( '300', 'woocustomcss' ),
			'400'        => __( '400', 'woocustomcss' ),
			'500'        => __( '500', 'woocustomcss' ),
			'600'        => __( '600', 'woocustomcss' ),
			'700'        => __( '700', 'woocustomcss' ),
			'800'        => __( '800', 'woocustomcss' ),
			'900'        => __( '900', 'woocustomcss' ),
			'bold'       => __( 'bold', 'woocustomcss' ),
			'bolder'     => __( 'bolder', 'woocustomcss' ),
			'normal'     => __( 'normal', 'woocustomcss' ),
			'lighter'    => __( 'lighter', 'woocustomcss' ),
			'inherit'    => __( 'inherit', 'woocustomcss' ),
			'unset'      => __( 'unset', 'woocustomcss' ),
		),
        'css' 		=> 'width:10em;',
        'default' 	=> '',
        'autoload' 	=> false,
        'desc_tip' 	=> true,
    ),
	array(
        'title' 	=> __('Category Box Padding', 'woocustomcss') ,
        'desc' 		=> __('Select Category box padding', 'woocustomcss') ,
        'id' 		=> 'cat_box_pading',
        'type' 		=> 'ms_dimension',
        'css' 		=> 'width:4em;',
        'default' 	=> '',
        'autoload' 	=> false,
        'desc_tip' 	=> true,
    ),
    array(
        'title'		=> __('Category Box Border', 'woocustomcss') ,
        'desc' 		=> __('Select Category box border size in pixles.', 'woocustomcss') ,
        'id' 		=> 'cat_box_bor',
        'type' 		=> 'ms_border',
        'css' 		=> 'width:4em;',
        'default' 	=> '',
        'autoload' 	=> false,
        'desc_tip' 	=> true,
    ),
    array(
        'title' 	=> __('Category Box  Radius', 'woocustomcss') ,
        'desc' 		=> __('Select Category box border radius in %', 'woocustomcss') ,
        'id' 		=> 'cat_box_bor_radis',
        'type' 		=> 'ms_dimension',
        'css' 		=> 'width:4em;',
        'default' 	=> '',
        'autoload' 	=> false,
        'desc_tip' 	=> true,
    ),
    array(
        'title' 	=> __('Category Box Shadow', 'woocustomcss') ,
        'desc' 		=> __('Add here the Category box shadow CSS.', 'woocustomcss') ,
        'id' 		=> 'cat_box_shadow',
        'type' 		=> 'text',
        'css' 		=> 'width:20em;',
        'default' 	=> '',
        'autoload' 	=> false,
        'desc_tip' 	=> true,
    ),
    array(
        'type' 		=> 'sectionend',
        'id' 		=> 'shop_cat_css_options',
    ),
	array(
        'title' 	=> __('Shop Page Product Loop CSS', 'woocustomcss') ,
        'type' 		=> 'title',
        'desc' 		=> '',
        'id' 		=> 'shop_product_css_options',
    ),
	array(
        'title' 	=> __('Product Title Font Family', 'woocustomcss') ,
        'desc' 		=> __('Add here the Product text Font family CSS. Black set default from body.', 'woocustomcss') ,
        'id' 		=> 'product_text_ff',
        'type' 		=> 'text',
        'css' 		=> 'width:20em;',
        'default' 	=> '',
        'autoload' 	=> false,
        'desc_tip' 	=> true,
    ),
    array(
        'title' 	=> __('Product Title Color', 'woocustomcss') ,
        'desc' 		=> __('Select product title color here.', 'woocustomcss') ,
        'id' 		=> 'product_title_text',
        'type' 		=> 'color',
        'css' 		=> 'width:6em;',
        'default' 	=> '#000000',
        'autoload' 	=> false,
        'desc_tip' 	=> true,
    ),
    array(
        'title' 	=> __('Product Title Size', 'woocustomcss') ,
        'desc' 		=> __('Select product title size in pixles.', 'woocustomcss') ,
        'id' 		=> 'product_title_size',
        'type' 		=> 'ms_size',
        'css' 		=> 'width:4em;',
        'default' 	=> '',
        'autoload' 	=> false,
        'desc_tip' 	=> true,
    ),
	array(
        'title' 	=> __('Product Title Font Weight', 'woocustomcss') ,
        'desc' 		=> __('Add here the Product Title Font Weight CSS.', 'woocustomcss') ,
        'id' 		=> 'product_title_fw',
		'type' 		=> 'select',
		'options'   => array(
			'100'        => __( '100', 'woocustomcss' ),
			'200'        => __( '200', 'woocustomcss' ),
			'300'        => __( '300', 'woocustomcss' ),
			'400'        => __( '400', 'woocustomcss' ),
			'500'        => __( '500', 'woocustomcss' ),
			'600'        => __( '600', 'woocustomcss' ),
			'700'        => __( '700', 'woocustomcss' ),
			'800'        => __( '800', 'woocustomcss' ),
			'900'        => __( '900', 'woocustomcss' ),
			'bold'       => __( 'bold', 'woocustomcss' ),
			'bolder'     => __( 'bolder', 'woocustomcss' ),
			'normal'     => __( 'normal', 'woocustomcss' ),
			'lighter'    => __( 'lighter', 'woocustomcss' ),
			'inherit'    => __( 'inherit', 'woocustomcss' ),
			'unset'      => __( 'unset', 'woocustomcss' ),
		),
        'css' 		=> 'width:10em;',
        'default' 	=> '',
        'autoload' 	=> false,
        'desc_tip' 	=> true,
    ),
    array(
        'title' 	=> __('Product Price Color', 'woocustomcss') ,
        'desc' 		=> __('Select product title color here.', 'woocustomcss') ,
        'id' 		=> 'product_price_text',
        'type' 		=> 'color',
        'css' 		=> 'width:6em;',
        'default' 	=> '#000000',
        'autoload' 	=> false,
        'desc_tip' 	=> true,
    ),
    array(
        'title' 	=> __('Product Price Size', 'woocustomcss') ,
        'desc' 		=> __('Select product price size in pixles.', 'woocustomcss') ,
        'id' 		=> 'product_price_size',
        'type' 		=> 'ms_size',
        'css' 		=> 'width:4em;',
        'default' 	=> '',
        'autoload' 	=> false,
        'desc_tip' 	=> true,
    ),
	array(
        'title' 	=> __('Product Price Font Weight', 'woocustomcss') ,
        'desc' 		=> __('Add here the Product Price Font Weight CSS.', 'woocustomcss') ,
        'id' 		=> 'product_price_fw',
        'type' 		=> 'select',
		'options'   => array(
			'100'        => __( '100', 'woocustomcss' ),
			'200'        => __( '200', 'woocustomcss' ),
			'300'        => __( '300', 'woocustomcss' ),
			'400'        => __( '400', 'woocustomcss' ),
			'500'        => __( '500', 'woocustomcss' ),
			'600'        => __( '600', 'woocustomcss' ),
			'700'        => __( '700', 'woocustomcss' ),
			'800'        => __( '800', 'woocustomcss' ),
			'900'        => __( '900', 'woocustomcss' ),
			'bold'       => __( 'bold', 'woocustomcss' ),
			'bolder'     => __( 'bolder', 'woocustomcss' ),
			'normal'     => __( 'normal', 'woocustomcss' ),
			'lighter'    => __( 'lighter', 'woocustomcss' ),
			'inherit'    => __( 'inherit', 'woocustomcss' ),
			'unset'      => __( 'unset', 'woocustomcss' ),
		),
        'css' 		=> 'width:10em;',
        'default' 	=> '',
        'autoload' 	=> false,
        'desc_tip' 	=> true,
    ),
	array(
        'title' 	=> __('Product Box Padding', 'woocustomcss') ,
        'desc' 		=> __('Select product box padding', 'woocustomcss') ,
        'id' 		=> 'product_box_pading',
        'type' 		=> 'ms_dimension',
        'css' 		=> 'width:4em;',
        'default' 	=> '',
        'autoload' 	=> false,
        'desc_tip' 	=> true,
    ),
    array(
        'title' 	=> __('Product Box Border', 'woocustomcss') ,
        'desc' 		=> __('Select product box border size in pixles.', 'woocustomcss') ,
        'id' 		=> 'product_box_bor',
        'type' 		=> 'ms_border',
        'css' 		=> 'width:4em;',
        'default' 	=> '',
        'autoload' 	=> false,
        'desc_tip' 	=> true,
    ),
    array(
        'title' 	=> __('Product Box Border Radius', 'woocustomcss') ,
        'desc' 		=> __('Select product box border radius in %', 'woocustomcss') ,
        'id' 		=> 'product_box_bor_radis',
        'type' 		=> 'ms_dimension',
        'css' 		=> 'width:4em;',
        'default' 	=> '',
        'autoload' 	=> false,
        'desc_tip' 	=> true,
    ),
    array(
        'title' 	=> __('Product Box Shadow', 'woocustomcss') ,
        'desc' 		=> __('Add here the product box shadow CSS.', 'woocustomcss') ,
        'id' 		=> 'product_box_shadow',
        'type' 		=> 'text',
        'css' 		=> 'width:20em;',
        'default' 	=> '',
        'autoload' 	=> false,
        'desc_tip' 	=> true,
    ),
    array(
        'type' 		=> 'sectionend',
        'id' 		=> 'shop_product_css_options',
    ),    
    array(
        'title' 	=> __('Webiste Product Buttons CSS', 'woocustomcss') ,
        'type' 		=> 'title',
        'desc' 		=> '',
        'id' 		=> 'btn_css_options',
    ),
	array(
        'title' 	=> __('Button Font Family', 'woocustomcss') ,
        'desc' 		=> __('Add here the Category text Font family CSS. Black set default from body.', 'woocustomcss') ,
        'id' 		=> 'btn_text_ff',
        'type' 		=> 'text',
        'css' 		=> 'width:20em;',
        'default' 	=> '',
        'autoload' 	=> false,
        'desc_tip' 	=> true,
    ),
	array(
        'title' 	=> __('Button Font Size', 'woocustomcss') ,
        'desc' 		=> __('Select font size in Pixels of the product cart button.', 'woocustomcss') ,
        'id' 		=> 'btn_font_size',
        'type' 		=> 'ms_size',
        'css' 		=> 'width:4em;',
        'default' 	=> '',
        'autoload' 	=> false,
        'desc_tip' 	=> true,
    ),
	array(
        'title' 	=> __('Button Font Weight', 'woocustomcss') ,
        'desc' 		=> __('Add here the Button Font Weight CSS.', 'woocustomcss') ,
        'id' 		=> 'btn_title_fw',
        'type' 		=> 'select',
		'options'   => array(
			'100'        => __( '100', 'woocustomcss' ),
			'200'        => __( '200', 'woocustomcss' ),
			'300'        => __( '300', 'woocustomcss' ),
			'400'        => __( '400', 'woocustomcss' ),
			'500'        => __( '500', 'woocustomcss' ),
			'600'        => __( '600', 'woocustomcss' ),
			'700'        => __( '700', 'woocustomcss' ),
			'800'        => __( '800', 'woocustomcss' ),
			'900'        => __( '900', 'woocustomcss' ),
			'bold'       => __( 'bold', 'woocustomcss' ),
			'bolder'     => __( 'bolder', 'woocustomcss' ),
			'normal'     => __( 'normal', 'woocustomcss' ),
			'lighter'    => __( 'lighter', 'woocustomcss' ),
			'inherit'    => __( 'inherit', 'woocustomcss' ),
			'unset'      => __( 'unset', 'woocustomcss' ),
		),
        'css'		=> 'width:10em;',
        'default' 	=> '',
        'autoload' 	=> false,
        'desc_tip' 	=> true,
    ),
    array(
        'title' 	=> __('Button Background Color', 'woocustomcss') ,
        'desc' 		=> __('Select color for buttons background color. The defalut color added by the woocustomcss CSS.', 'woocustomcss') ,
        'id' 		=> 'btn_clr',
        'type' 		=> 'color',
        'css' 		=> 'width:6em;',
        'default' 	=> '#3c3c3c',
        'autoload' 	=> false,
        'desc_tip' 	=> true,
    ),
    array(
        'title' 	=> __('Button Text Color', 'woocustomcss') ,
        'desc' 		=> __('Select color for buttons background color. The defalut color added by the woocustomcss CSS.', 'woocustomcss') ,
        'id' 		=> 'btn_txt_clr',
        'type' 		=> 'color',
        'css' 		=> 'width:6em;',
        'default' 	=> '#3c3c3c',
        'autoload' 	=> false,
        'desc_tip' 	=> true,
    ),
    array(
        'title' 	=> __('Button Hover Background Color', 'woocustomcss') ,
        'desc' 		=> __('Select color for buttons hover background color. The defalut color added by the woocustomcss CSS.', 'woocustomcss') ,
        'id' 		=> 'btn_hclr',
        'type' 		=> 'color',
        'css' 		=> 'width:6em;',
        'default' 	=> '#3c3c3c',
        'autoload' 	=> false,
        'desc_tip' 	=> true,
    ),
    array(
        'title' 	=> __('Button Hover Text Color', 'woocustomcss') ,
        'desc' 		=> __('Select color for buttons hover background color. The defalut color added by the woocustomcss CSS.', 'woocustomcss') ,
        'id' 		=> 'btn_htxt_clr',
        'type' 		=> 'color',
        'css' 		=> 'width:6em;',
        'default' 	=> '#3c3c3c',
        'autoload' 	=> false,
        'desc_tip' 	=> true,
    ),    
    array(
        'title'		=> __('Button Padding', 'woocustomcss') ,
        'desc' 		=> __('Select product button Padding', 'woocustomcss') ,
        'id' 		=> 'product_btn_padding',
        'type' 		=> 'ms_dimension',
        'css' 		=> 'width:4em;',
        'default' 	=> '',
        'autoload' 	=> false,
        'desc_tip' 	=> true,
    ),
    array(
        'title' 	=> __('Button Border Radius', 'woocustomcss') ,
        'desc' 		=> __('Select button border radius in Pixels', 'woocustomcss') ,
        'id' 		=> 'btn_bor_radius',
        'type' 		=> 'ms_dimension',
        'css' 		=> 'width:4em;',
        'default' 	=> '',
        'autoload' 	=> false,
        'desc_tip' 	=> true,
    ),
    array(
        'type' 		=> 'sectionend',
        'id' 		=> 'btn_css_options',
    ),
	array(
        'title' 	=> __('Product detail Page CSS', 'woocustomcss') ,
        'type' 		=> 'title',
        'desc' 		=> '',
        'id' 		=> 'pro_detail_css_options',
    ),
	array(
        'title' 	=> __('Product Title Font Family', 'woocustomcss') ,
        'desc' 		=> __('Add here the Product details page text Font family CSS. Black set default from body.', 'woocustomcss') ,
        'id' 		=> 'pro_detail_text_ff',
        'type' 		=> 'text',
        'css' 		=> 'width:20em;',
        'default' 	=> '',
        'autoload' 	=> false,
        'desc_tip' 	=> true,
    ),
    array(
        'title' 	=> __('Product Title Color', 'woocustomcss') ,
        'desc' 		=> __('Select product title color here.', 'woocustomcss') ,
        'id' 		=> 'pro_detail_title_text',
        'type' 		=> 'color',
        'css' 		=> 'width:6em;',
        'default' 	=> '#000000',
        'autoload' 	=> false,
        'desc_tip' 	=> true,
    ),
    array(
        'title' 	=> __('Product Title Size', 'woocustomcss') ,
        'desc' 		=> __('Select product title size in pixles.', 'woocustomcss') ,
        'id' 		=> 'pro_detail_title_size',
        'type' 		=> 'ms_size',
        'css' 		=> 'width:4em;',
        'default' 	=> '',
        'autoload' 	=> false,
        'desc_tip' 	=> true,
    ),
	array(
        'title' 	=> __('Product Title Font Weight', 'woocustomcss') ,
        'desc' 		=> __('Add here the Product Title Font Weight CSS.', 'woocustomcss') ,
        'id' 		=> 'pro_detail_title_fw',
        'type' 		=> 'select',
		'options'   => array(
			'100'        => __( '100', 'woocustomcss' ),
			'200'        => __( '200', 'woocustomcss' ),
			'300'        => __( '300', 'woocustomcss' ),
			'400'        => __( '400', 'woocustomcss' ),
			'500'        => __( '500', 'woocustomcss' ),
			'600'        => __( '600', 'woocustomcss' ),
			'700'        => __( '700', 'woocustomcss' ),
			'800'        => __( '800', 'woocustomcss' ),
			'900'        => __( '900', 'woocustomcss' ),
			'bold'       => __( 'bold', 'woocustomcss' ),
			'bolder'     => __( 'bolder', 'woocustomcss' ),
			'normal'     => __( 'normal', 'woocustomcss' ),
			'lighter'    => __( 'lighter', 'woocustomcss' ),
			'inherit'    => __( 'inherit', 'woocustomcss' ),
			'unset'      => __( 'unset', 'woocustomcss' ),
		),
        'css'		=> 'width:10em;',
        'default' 	=> '',
        'autoload' 	=> false,
        'desc_tip' 	=> true,
    ),
    array(
        'title' 	=> __('Product Price Color', 'woocustomcss') ,
        'desc' 		=> __('Select product title color here.', 'woocustomcss') ,
        'id' 		=> 'pro_detail_price_text',
        'type' 		=> 'color',
        'css' 		=> 'width:6em;',
        'default' 	=> '#000000',
        'autoload' 	=> false,
        'desc_tip' 	=> true,
    ),
    array(
        'title' 	=> __('Product Price Size', 'woocustomcss') ,
        'desc' 		=> __('Select product price size in pixles.', 'woocustomcss') ,
        'id' 		=> 'pro_detail_price_size',
        'type' 		=> 'ms_size',
        'css' 		=> 'width:4em;',
        'default' 	=> '',
        'autoload' 	=> false,
        'desc_tip' 	=> true,
    ),
	array(
        'title' 	=> __('Product Price Font Weight', 'woocustomcss') ,
        'desc' 		=> __('Add here the Product Price Font Weight CSS.', 'woocustomcss') ,
        'id' 		=> 'pro_detail_price_fw',
        'type' 		=> 'select',
		'options'   => array(
			'100'        => __( '100', 'woocustomcss' ),
			'200'        => __( '200', 'woocustomcss' ),
			'300'        => __( '300', 'woocustomcss' ),
			'400'        => __( '400', 'woocustomcss' ),
			'500'        => __( '500', 'woocustomcss' ),
			'600'        => __( '600', 'woocustomcss' ),
			'700'        => __( '700', 'woocustomcss' ),
			'800'        => __( '800', 'woocustomcss' ),
			'900'        => __( '900', 'woocustomcss' ),
			'bold'       => __( 'bold', 'woocustomcss' ),
			'bolder'     => __( 'bolder', 'woocustomcss' ),
			'normal'     => __( 'normal', 'woocustomcss' ),
			'lighter'    => __( 'lighter', 'woocustomcss' ),
			'inherit'    => __( 'inherit', 'woocustomcss' ),
			'unset'      => __( 'unset', 'woocustomcss' ),
		),
        'css' 		=> 'width:10em;',
        'default' 	=> '',
        'autoload' 	=> false,
        'desc_tip' 	=> true,
    ),
    array(
        'type' 		=> 'sectionend',
        'id' 		=> 'pro_detail_css_options',
    ),
);
